CREATE TABLE IF NOT EXISTS posts (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  community_id BIGINT NOT NULL REFERENCES communities (id) ON DELETE CASCADE,
  views BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_posts_community_id ON posts (community_id);

CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts (user_id);
